EcoVia/urls.py
from django.contrib import admin
from django.urls import path
from Aplicacion.views import *

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",home,),
    path("home/",home,name="home"),
    path("registrarse/",registrar_usuario,name="registrarse"),
    path("iniciar_sesion/",iniciar_sesion,name="iniciar_sesion"),
    path("logout/", cerrar_sesion, name="cerrar_sesion"),
    path("crear_comentario/", crear_comentarios, name="crear_comentarios"),
    path('ver_comentarios/', ver_comentarios, name='ver_comentarios'),
    path('eliminar_comentario/<int:id>/', eliminar_comentario, name='eliminar_comentario'),
    path('editar_comentario/<int:id>/', editar_comentario, name='editar_comentario'),
    path('crear_respuesta/', crear_respuesta, name='crear_respuesta'),
   
]

Aplicacion/models.py
from django.db import models
from django.contrib.auth.models import User

class Comentario(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField(max_length=200)
    creacion = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'comentado por {self.usuario.username}'

class Respuesta(models.Model):
    comentario = models.ForeignKey(Comentario, on_delete=models.CASCADE)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    texto = models.TextField(max_length=200)
    fecha = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f'Respuesta a "{self.comentario}" por {self.usuario.username}'

Aplicacion/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *

class RegistroForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class ComentarioForm(forms.ModelForm):
    class Meta:
        model = Comentario
        fields = ('texto',)
        
class RespuestaForm(forms.Form):
    comentario_id = forms.IntegerField(widget=forms.HiddenInput())
    texto = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}))

Aplicacion/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.forms import  AuthenticationForm # para crear formularios
from django.contrib.auth import login,logout,authenticate
from django.db import IntegrityError
from .forms import *
from .models import *
from django.contrib.auth.decorators import login_required
# Create your views here.

def home(request):
    return render(request, "home.html")
from django.shortcuts import render, redirect
from .forms import RegistroForm

def registrar_usuario(request):
    form = RegistroForm()
    if request.method == 'POST':
        form = RegistroForm(request.POST)
        if form.is_valid():
            user = form.save()  # Guardar el nuevo usuario en la base de datos
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(request, username=username, password=password)
            login(request, user)  # Iniciar sesión automáticamente
            return redirect('home')  # Redirigir a la página de inicio después del registro exitoso
    return render(request, 'registro.html', {'form': form})

def iniciar_sesion(request):
    if request.method == "GET":
        return render(request, 'iniciar_sesion.html',{"form":AuthenticationForm})
    else:
        user = authenticate(request,username=request.POST["username"],password=request.POST["password"])
        if user is None: 
            return render(request, 'iniciar_sesion.html',{"form":AuthenticationForm,"error":"nombre de usuario o contraseña incorrecto"})    
        else:
            login(request,user)
            return redirect("home")
            
def cerrar_sesion(request):
    logout(request)
    return redirect("home")

def ver_comentarios(request):
    comentarios = Comentario.objects.all()
    respuestas = Respuesta.objects.all()

    if request.method == 'POST':
        respuesta_form = RespuestaForm(request.POST)
        if respuesta_form.is_valid():
            id = respuesta_form.cleaned_data['id']
            texto = respuesta_form.cleaned_data['texto']
            comentario = Comentario.objects.get(id=id)
            respuesta = Respuesta(comentario=comentario, usuario=request.user, texto=texto)
            respuesta.save()
            return redirect('ver_comentarios')
    else:
        respuesta_form = RespuestaForm()

    return render(request, 'ver_comentarios.html', {'comentarios': comentarios, 'respuestas': respuestas, 'respuesta_form': respuesta_form})

@login_required
def crear_respuesta(request):
    if request.method == 'POST':
        respuesta_form = RespuestaForm(request.POST)
        if respuesta_form.is_valid():
            comentario_id = respuesta_form.cleaned_data['comentario_id']
            texto = respuesta_form.cleaned_data['texto']
            comentario = Comentario.objects.get(id=comentario_id)
            respuesta = Respuesta(comentario=comentario, usuario=request.user, texto=texto)
            respuesta.save()
            return redirect('ver_comentarios')
    else:
        respuesta_form = RespuestaForm()
        
    return render(request, 'crear_respuesta.html', {'respuesta_form': respuesta_form})

@login_required
def eliminar_comentario(request, id):
  comentario = Comentario.objects.get(id=id)
  comentario.delete()
  return redirect('ver_comentarios')

@login_required
def editar_comentario(request,id):
    comentario = get_object_or_404(Comentario, id=id)
    
    if request.method == 'POST':
        form = ComentarioForm(request.POST, instance=comentario)
        if form.is_valid():
            form.save()
            return redirect('ver_comentarios')
    else:
        form = ComentarioForm(instance=comentario)
    
    return render(request, 'editar_comentario.html', {'form': form})
    
@login_required
def crear_comentarios(request):
    if request.method == 'GET':
        form = ComentarioForm()
        return render(request, 'crear_comentario.html', {'form': form})  
    else:
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit=False)
            comentario.usuario = request.user  # Asignar el usuario actual al comentario
            comentario.save()
            return redirect('ver_comentarios')
        else:
             print(form.errors)
    return render(request, 'crear_comentario.html', {'form': form})

Aplicacion/templates/crear_comentario.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<form class="comment-form" method="POST" action="{% url 'crear_comentarios' %}"> 
  {{ error }}
  {% csrf_token %}

  <div class="form-group">
    <label for="id_texto">Texto:</label>
    {{ form.texto }}
  </div>

  <button type="submit">Enviar</button>
</form>
{% endblock %}

Aplicacion/templates/crear_respuesta.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block content %}
<form method="POST" action="{% url 'crear_respuesta' %}">
    {% csrf_token %}
    <input type="hidden" name="comentario_id" value="{{ comentario.id }}">
    {{ respuesta_form.as_p }}
    <button type="submit">Responder</button>
  </form>
{% endblock %}

Aplicacion/templates/editar_comentario.html
{% extends 'layouts/base.html' %}

{% load static %}

{% block content %}
<form class="comment-form" method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Guardar cambios</button>
</form>
{% endblock %}

Aplicacion/templates/home.html
{% extends 'layouts/base.html'%}
{% load static%}
{%block content%}
<main class="contianer py-5">
    <section class="card card-body">
        <h1 class="display text-center">¡ Bienvenido !</h1>
        <p>Esta página es para su información de reciclar y pueda comentar lo que usted considere importante.</p>
        <div class="text-center">
            <a class="btn btn-primary" href="/iniciar_sesion/">Iniciar Sesion</a>
            <a class= "btn btn-primary"href="/registrarse/">Registrarse </a>
        </div>
    </section>
</main>
{%endblock%}

Aplicacion/templates/iniciar_sesion.html
{%extends 'layouts/base.html'%}
{%block content%}
{%load static %}
<!-- {% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
{% endblock %}  por si acaso -->
<main class="container">
    <div class="row mt-5" > <!-- mt-5 sirve para dejar un espacio con la parte superio de la pagina-->
        <section class="col-md-4 offset-md-4">
          
                <form action="" method="POST" class="card custom-card-body">
                    {% csrf_token %}
                
                    <h1 class="text-center">iniciar sesion</h1>
                     {{error}}
                
               <div class="mb3">
                <label for="username"> Nombre de Usuario:</label>
                <input type="text" name="username" class="form-control" placeholder="nombre de usuario" id="username">
               </div>
               <div class="mb3">
                <label for="password">contraseña:</label>
                <input type="password" name="password" class="form-control" placeholder="contraseña" id="password">
               </div>
               <br>
                <button class="btn btn-primary">iniciar sesion</button>
                <br>
                <div class="pie-form">
                    <a href="#"class="custom-text-color">¿Perdiste tu contraseña?</a>
                    <br>
                    <a href="/registrarse/"class="custom-text-color">¿No tienes Cuenta? 
                        Registrate</a>
                    </div>
                <div class="inferior text-center" >
                    <a href="/home/"class="custom-text-color">Volver</a>
                </div>
                </form>
        </section>
    </div>
</main>
{%endblock%}   

Aplicacion/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>EcoVia</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}"> -->
    {% block style %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    {% endblock %}

  </head>
<body>
    <nav class="navbar navbar-expand-lg bg-dark navbar-dark">
        <div class="container">
          <a class="navbar-brand" href="/home/"> <img src="{% static '/imagenes/logo.png' %}" alt="EcoVia" style="max-width: 70px; max-height: 70px;">EcoVia</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item" >
                    <a href="/home" class="nav-link">Pagina principal </a>
                   </li>
                  
                   <li class="nav-item" >
                    <a href="/ver_comentarios" class="nav-link">Ver Comentarios </a>
                   </li>
                   
                   {% if user.is_authenticated %}
                   <li class="nav-item" >
                    <a href="/crear_comentario" class="nav-link">Crear Comentario </a>
                   </li>
                   <li class="nav-item" >
                      <a href="/logout"class="nav-link">Cerrar Sesion </a>
                  </li>
                  {% else %}
                      <li class="nav-item" >
                        <a href="/registrarse" class="nav-link">Registrarse </a>
                      </li>
                      <li class="nav-item" >
                        <a href="/iniciar_sesion" class="nav-link">Iniciar Sesion </a>
                  {% endif %}
                  
                   
          </div>
        </div>
      </nav>
    {% block content %}
   
    {% endblock %}
   
    <footer >
      <p>&copy; 2023 Mi Página. Todos los derechos reservados.</p>
    </footer>
</body>
</html>

Aplicacion/templates/registro.html
{% extends 'layouts/base.html' %}
{% block content %}
  <div class="d-flex justify-content-center align-items-center vh-100 gray-bg">
    <form method="POST" class="registro-form registration-form">
      {% csrf_token %}
      <h1>Registro</h1>
      {{error}}
      <div class="form-group">
        <label for="{{ form.username.id_for_label }}">Nombre de usuario:</label>
        {{ form.username }}
      </div>
      <div class="form-group">
        <label for="{{ form.email.id_for_label }}">Correo electrónico:</label>
        {{ form.email }}
      </div>
      <div class="form-group">
        <label for="{{ form.password1.id_for_label }}">Contraseña:</label>
        {{ form.password1 }}
      </div>
      <div class="form-group">
        <label for="{{ form.password2.id_for_label }}">Confirmar contraseña:</label>
        {{ form.password2 }}
      </div>
      <button type="submit" class="btn btn-primary">Registrarse</button>
    </form>
  </div>
{% endblock %}

Aplicacion/templates/responder_comentario.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Enviar respuesta</button>
  </form>
{% endblock %}

Aplicacion/templates/ver_comentarios.html
{%extends 'layouts/base.html'%}
{% load static %}
{% block content %}
{% for comentario in comentarios %}
    <div class="comentario">
        <h3 class="comentario-usuario">{{ comentario.usuario }}</h3>
        <p class="comentario-texto">{{ comentario.texto }}</p>
        <p class="comentario-texto">{{ comentario.creacion }}</p>
        {% for respuesta in respuestas %}
            {% if respuesta.comentario.id == comentario.id %}
                <div class="respuesta">
                    <h4 class="respuesta-usuario">{{ respuesta.usuario }}</h4>
                    <p class="respuesta-texto">{{ respuesta.texto }}</p>
                </div>
            {% endif %}
        {% endfor %}
        
        {% if comentario.usuario == request.user %}
            <a href="{% url 'editar_comentario' comentario.id %}">Editar</a> 
            <a href="{% url 'eliminar_comentario' comentario.id %}">Eliminar</a>
        {% endif %}
        
        {% if user.is_authenticated %}
            <form class="respuesta-form" method="POST" action="{% url 'crear_respuesta' %}">
                {% csrf_token %}
                <input type="hidden" name="comentario_id" value="{{ comentario.id }}">
                {{ respuesta_form.texto }}
                <button type="submit">Responder</button>
            </form>
        {% endif %}
    </div>
{% endfor %}
{% endblock %}